[package]
name = "cli-tuner"
version = "0.1.0"
authors = ["da.lum <david.lum91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stft = { path = "stft" }
cpal = "*"
num = "0.3.1"
